CREATE TABLE IF NOT EXISTS units (
    id UUID PRIMARY KEY,
    unit_number TEXT NOT NULL UNIQUE,
    unit_type TEXT NOT NULL CHECK (
        unit_type IN ('PUBLIC_HOUSING', 'COMMERCIAL', 'RESIDENTIAL')
    ),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);